[versions]

leaf-loader = "1.7.1"
leaf-loom = "0.7.3"
zomboid = "42.21.0"

[libraries]

leaf-loader = { module = "dev.aoqia.leaf:loader", version.ref = "leaf-loader" }
zomboid = { module = "com.theindiestone:zomboid", version.ref = "zomboid" }

[plugins]

leaf-loom = { id = "dev.aoqia.leaf.loom", version.ref = "leaf-loom" }
